apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: konflux-ci
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: konflux-ci
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
