apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/image-controller/config/default?ref=103df04d173a93937ca20c4c0baa8571242b28e2

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: 103df04d173a93937ca20c4c0baa8571242b28e2

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
