apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/redhat-appstudio/application-service/config/default?ref=a47ecf4f599cd717bf6550072015a2cb1f33c400
components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: a47ecf4f599cd717bf6550072015a2cb1f33c400
configMapGenerator:
  - literals:
      - GITHUB_ORG=susdas-qe
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
namespace: application-service
